### ISSUE TITLE
on "s5.cx" and last "sw.js" stop all videos at 128 chunks with wait

### ISSUE THREAD

**Issue by parajbs** [s5-dev/web-proxy#1]
Hello **@redsolver,**

I have problems with all videos on "s5.cx" and last "sw.js".
They all stop at 128 chunks, if I then fast forward a little bit, everything works great until the end.

So it's funny that he always stops at 128 chunks in all videos.

https://s5.cx/s5/blob/urqYSH6GcjHUsB2ZDQboo3vJZB9RVZ8GcrOGpdqJi0eAqMRBPBEoEsb0HYbXp7LxOGfZ3WUpKbqkx4TytpDRcALI7gOAAAAAAJh_beaWeo4UkYTcjWFY5oWKcfVn2BvZvBqi3GO2VxK9dovuueso?mediaType=video%2Fmp4

I was able to fix the issue on my local testnet by adding this code to sw.js after line 443:
`downloadingChunkLock[chunkLockKey] = false;`

previously:
```
console.debug('[chunk] wait for ' + chunk);
// sub?.cancel();
while (downloadingChunkLock[chunkLockKey] === true) {
  // TODO Risk for infinite loop, add timeout
  await new Promise(r => setTimeout(r, 10));
}
```

afterward:
```
console.debug('[chunk] wait for ' + chunk);
// sub?.cancel();
while (downloadingChunkLock[chunkLockKey] === true) {
  // TODO Risk for infinite loop, add timeout
  await new Promise(r => setTimeout(r, 10));
  downloadingChunkLock[chunkLockKey] = false;
}
```

I'm sure this isn't the solution, but for now it works fine with sw.js.
No video stops anymore.

Can you take a look?

**Comment by redsolver** [comment]
Fixed in https://github.com/s5-dev/web-proxy/commit/a9e5ec14ab6d90a094d50111a7b63c4aeb1f2256, please re-open if not
